name: CI - XYZ Bornes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Xyz.Bornes.Tests/Xyz.Bornes.Tests.csproj

      - name: Build
        run: dotnet build Xyz.Bornes.Tests/Xyz.Bornes.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test Xyz.Bornes.Tests/Xyz.Bornes.Tests.csproj --configuration Release --no-build

      - name: Build Docker image
        run: docker build -t xyz-bornes-simulateur .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'xyz-bornes-simulateur'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'